### ISSUE TITLE
Add support for 2023.1 version

### ISSUE THREAD

**Issue by GauthierPLM** [AntonShuvaev/jet-client-support#1]
### Is your feature request related to a problem?

The plugin is currently only available for 2022.* releases.

### Describe the solution you'd like

I'd like to be able to test the plugin on the latest EAP / beta as the 2023.1 version is close to be released.

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue, I'll support it in the next release, next week.

**Comment by GauthierPLM** [comment]
I confirm the plugin works well with 2023.1.
