### ISSUE TITLE
Add a way to predefine local variables when sharing a colleciton

### ISSUE THREAD

**Issue by GauthierPLM** [AntonShuvaev/jet-client-support#10]
### Is your feature request related to a problem?

Currently, only shared variables are carried along a folder and there are no way to specify which local variables can be set. This complicate the discoverability of local variables in a folder.

### Describe the solution you'd like

Add a way to list the local variables that could be set by a developer in a folder, exported without their value. This can be useful e.g. to set values specific to a developer or machine (ex: API credential, local port / URL,...) that are not suitable to be added as shared variables or that would expose information.

We could even imagine a way to specify which variables are expected by an environment group, like the URL / Port in the "application environment" env, and user ID / email / API Credential for an "API Instance" env.

### Additional context

JetClient could use JSON Schema as a source for this as it is compatible with JSON5. We could also imagine exporting the current local variables to a JSON Schema to generate it as a draft.

**Comment by AntonShuvaev** [comment]
You can specify shared variables with references to local variables like `username: {{localUsername}}` or even `username: {{username}}`. They will not be fully resolved until you specify corresponding local variables. Also you can add comments with description.
<img width="838" alt="Screenshot 2023-03-29 at 18 35 02" src="https://user-images.githubusercontent.com/25157138/228591469-d906edca-4f58-4a85-80e7-c02fea9904dc.png">

**Comment by AntonShuvaev** [comment]
I will be closing this issue as I think the solution provided above is sufficient for most use cases.
