### ISSUE TITLE
jc.runFolder doesnt work

### ISSUE THREAD

**Issue by dudatom4** [AntonShuvaev/jet-client-support#100]
Today i updated Jetclient to the newest version. Before the update everything wokred perfectly.

When i try to use command await jc.runFolder("FOLDER X")

Error is shown:
TypeError: invokeMember (runFolder) on io.jetclient.js.bindings.s failed due to: Unknown identifier: runFolder

It looks like the command doesnt exists. Is it bug?

Thanks

**Comment by AntonShuvaev** [comment]
The `runFolder` will be reintroduced in the next version, which should be released tomorrow or on Monday. Sorry for the inconvenience.
