### ISSUE TITLE
Add documentation in the test library type definition file

### ISSUE THREAD

**Issue by GauthierPLM** [AntonShuvaev/jet-client-support#11]
### Is your feature request related to a problem?

There is no documentation beyond the method' declaration displayed in the IDE when writing a test / pre-request script.

### Describe the solution you'd like

Adding documentation to jet-client.d.ts would allow it to be displayed directly in the IDE when writing code instead of having to lookup in the lib documentation on Github.

**Comment by AntonShuvaev** [comment]
Will add in the next release.

**Comment by AntonShuvaev** [comment]
Added in 2023.1.6
