### ISSUE TITLE
Generate code snippet from request

### ISSUE THREAD

**Issue by millsks** [AntonShuvaev/jet-client-support#15]
### Is your feature request related to a problem?

No problem.  New feature request.

### Describe the solution you'd like

A drop down button or side panel that will generate code snippets based on the current request and the language selected from a drop down. Similar to how Postman does it today.

**Comment by AntonShuvaev** [comment]
Good suggestion, will add it in the next release.

**Comment by AntonShuvaev** [comment]
The feature is implemented in version 2023.1.9.
