### ISSUE TITLE
Question: How can we suppress a redirect on a Get Request?

### ISSUE THREAD

**Issue by inkstain** [AntonShuvaev/jet-client-support#16]
Hi,

Please let me know if such questions should be sent elsewhere

I have a Get request that gets redirected but I need to suppress the redirect to be able to parse the headers of the initial response. In Postman there is a toggle for this in the Settings for the request, and in the bundled http-client there is a `# @no-redirect` directive that can be used. I looked through the docs but did not find anything related to this.

Thanks!

ink

**Comment by AntonShuvaev** [comment]
Hi, 

You can disable `Follow redirects` in `Settings > Tools > JetClient`.
