### ISSUE TITLE
Add support for OAuth2 implicit flow

### ISSUE THREAD

**Issue by marshallthornton** [AntonShuvaev/jet-client-support#19]
### Is your feature request related to a problem?

Trying to get the authentication working when using Amazon Cognito as the OAuth2 provider.

### Describe the solution you'd like

Add support for the Implicit flow. If you specify the response type as `token` when hitting the authorize endpoint with implicit grant enabled for that client then it will return the access token directly in the redirect with no extra steps needed.

### Additional context

Their /oauth2/token endpoint requires a separate client since it requires a client secret to utilize. When setting up app clients inside Cognito, if you choose to support Authentication Code flow then it won't allow you to select the Client Credentials. Same if you select Client Credentials, it won't let you then select Authentication Code.

**Comment by marshallthornton** [comment]
I was able to get things working, most of the problem is that Googling for how to set this up with other clients like Postman and Insomnia all return steps saying to use the Implicit Grant flow.

It looks like, when creating the new app client, you can specify it to run as a Public client that uses the Authorization Code Grant flow but then manually override it to generate a Client Secret during creation. As long as it has a client secret to send up, you can then utilize the /oauth2/token endpoint even if you didn't specifically select to use it during client creation.

So create the app client with the following:
* Type: Public client or Other
* Client Secret: Generate a client secret
* Authentication Flows: ALLOW_USER_PASSWORD_AUTH
* Grant Types: Authorization code grant
* Scopes and other settings can be whatever you need.

After that you can setup the auth settings as follows:
* Grant Type: Authorization Code
* Auth URL: <Cognito hosted endpoint URL>/login
* Access Token URL: <Cognito hosted endpoint URL>/oauth2/token
* Callback URL: http://localhost
* Client ID: <ID of app client created>
* Client Secret: <secret of app client created>
* Scope: <scope you setup on the client>

If something like this could be added to the documentation on how to setup Cognito OAuth2 with JetClient then it might save other people from the struggle of Googling it and only finding people talking about using Implicit flow with other REST clients.

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion! I'm going to implement implicit flow in the next update.

**Comment by AntonShuvaev** [comment]
OAuth2 implicit flow has been implemented. Please update to version 2023.1.10.
