### ISSUE TITLE
Add support for request / response visualisation

### ISSUE THREAD

**Issue by GauthierPLM** [AntonShuvaev/jet-client-support#2]
### Is your feature request related to a problem?

It seems it is not yet possible to visualise the requests / response sent in a format similar to Postman' console. having such visualisation can be very useful to debug missing variables or to see the exact content sent to the server.

### Describe the solution you'd like

I'd suggest to integrate a "console" similar to Postman' console in the services tool window that could summarise the requests and their responses.

Using the service tool window will allow to either visualise all requests sent in a single view, or visualise them per collection / JetClient requests (similarly to DataGrip' visualisation of SQL requests).

**Comment by AntonShuvaev** [comment]
Good suggestion, will add to roadmap.

**Comment by AntonShuvaev** [comment]
Version 2024.1.6 now includes a console in the Services tool window for viewing requests, responses, and script output.
