### ISSUE TITLE
API Request to an application using a self-signed certificate will not work

### ISSUE THREAD

**Issue by vaio2005** [AntonShuvaev/jet-client-support#20]
**Describe the bug**

Applications using a self-signed certificate not running on a standard port won't work

**Steps to reproduce**

1. Have an application expose an API to a non-standard port with a self-signed certificate
2. Execute a request to that API
3. Allow the self-signed certificate
4. Observe the error  `Error: Certificate for IP> doesn't match any of the subject alternative names: []`

**Expected behavior**

The request should go through, and retrieve the response of the API request.

**Environment information:**
- OS: Windows 10 22H2 19045.2846
- IDE version: IDEA 2023.1.1 Ultimate Edition #IU-231.8770.65
- plugin version: 2023.1.9-231

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. Will look into it.

**Comment by AntonShuvaev** [comment]
I've added an option to disable certificate hostname verification `Settings > Tools > JetClient > Host name verification`. Please update to version 2023.1.10 and disable this option to resolve the problem.
