### ISSUE TITLE
Follow standard "open in split view" JetBrains behaviour when focused on draft in tool window

### ISSUE THREAD

**Issue by dencoSeca** [AntonShuvaev/jet-client-support#21]
### Description
I use JetBrains products almost entirely from the keyboard, and In my typical workflow using JetClient (which is pure awesomeness by the way 😊👏) I want to open a JetClient request in split view to the side of the request handler code I'm working on. 

### Problem
Currently the standard shortcut for _**Open In Right Split**_ (shift + return), when a request is focused in the tool window folder structure, doesn't behave the same as everywhere else in JetBrains IDEs, but instead opens the draft in the editor window in place of the current file. 

### Solution
- Follow the convention of **_shift + return_** executing _**Open In Right Split**_.
- Possibly add a context menu on right clicking a draft for mouse users as well?

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. Will do it in the next update.

**Comment by AntonShuvaev** [comment]
Implemented in 2023.1.11. Now, you can open request in a right split view using Shift + Return or Alt + Double-click.
