### ISSUE TITLE
Path variables are not displayed when you import an openapi (swagger) file

### ISSUE THREAD

**Issue by gkdevone** [AntonShuvaev/jet-client-support#23]
**Describe the bug**

When you import an openapi file 
and you navigate to an imported request whose url is like for example {{baseUrl}}/persons/{uid}
the path variables editor (for uid in this case) is not displayed.

You have to click in the url text and press for example a space 
in order for the editor to wake up and display the path variables

**Environment information:**
- OS: macos ventura 13.3.1
- IDE version: IntelliJ IDEA 2023.1.2
- plugin version: 2023.1.10-231

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. Will fix in the next update.

**Comment by AntonShuvaev** [comment]
Fixed in 2023.1.11
