### ISSUE TITLE
Import sync folder does not keep folder in sync after importing

### ISSUE THREAD

**Issue by gkdevone** [AntonShuvaev/jet-client-support#25]
**Describe the bug**
After importing a Sync Folder in JetClient tree the folder is not acting like a sync folder.
It does not monitor diffs and buttons Show Diff, Save and Restore are disabled.

**Steps to reproduce**
1. Create a Collection and sync it to a path like for example /Users/geo/jetclient
2. Create a Folder in collection with sync enabled
3. Add some requests in folder 

at this point everything works as expected

4. Either import the /Users/geo/jetclient sync folder to another intellij project 
    or just delete the collection from jetclient tree and reimport the /Users/geo/jetclient sync folder
5. Now the collection does not act as synced

**Environment information:**

- OS: macos ventura 13.3.1
- IDE version: IntelliJ IDEA 2023.1.2
- plugin version: 2023.1.10-231

**Comment by AntonShuvaev** [comment]
Fixed in 2023.1.11
