### ISSUE TITLE
Multipart/form with file - Content length too long

### ISSUE THREAD

**Issue by dan-sherwin** [AntonShuvaev/jet-client-support#27]
I am using JetClient to test some multipart/form upload of files, which I see jetClient can do.  I am using it with a paid license.  When I select an image file of size 184K for one of the parts and try to submit the request, I get the message "Error: Content length is too long: 184882".

I pulled up WireShark and I did not see any requests being made on the network so this isn't coming from the API server.  Is this some kind of limit imposed within JetClient, and if so, is it adjustable?

}Dan

**Comment by AntonShuvaev** [comment]
Thanks for reporting. Will fix asap.

**Comment by AntonShuvaev** [comment]
The bug is fixed. Please update to version 2023.1.12.

**Comment by dan-sherwin** [comment]
Works like a champ.  Thank you and great job.
