### ISSUE TITLE
Raw data and headers of the Request being sent

### ISSUE THREAD

**Issue by dan-sherwin** [AntonShuvaev/jet-client-support#29]
### Is your feature request related to a problem?

No problem associated with this feature request.

### Describe the solution you'd like

When a request is made, there are tabs in the response area to see the raw data received and all the headers that were sent with the response.  There are times when it would be useful to see the raw data and headers of the actual request being sent, to know for a fact what is being sent.  Right now, when I need to verify the data on the wire being sent for the request, I have to fire up Wireshark to see it.  It would be convenient if that raw data/headers were available from within JetClient.

**Comment by AntonShuvaev** [comment]
You can open the Generate Code Snippet dialog from the dropdown near the Send button or by pressing `Alt+Shift+Cmd+G`. In the Request tab, you can select HTTP to view the plain HTTP request.
