### ISSUE TITLE
Add support for importing Postman requests / collections

### ISSUE THREAD

**Issue by GauthierPLM** [AntonShuvaev/jet-client-support#3]
### Is your feature request related to a problem?

I'd like to migrate my APIs from Postman to JetClient.

### Describe the solution you'd like

Postman using JSON format, the plugin would be able to read the exported request / collection / workspace(?) into JetClient format.

### Additional context

I create this issue to follow it and know when it'll be made available, as I could read more format will be added later.

**Comment by AntonShuvaev** [comment]
I'm planning to implement this soon.

**Comment by GauthierPLM** [comment]
I noticed a « Synchronization » feature on the import dialog, but I couldn't find any documentation about it. What does it do?

**Comment by AntonShuvaev** [comment]
Each folder can have enabled or disabled synchronization and root folders can have path where to sync state.
When you import a folder as well as when you create a new folder, you can choose if you want to enable or disable synchronization and path where to store sync files. You can change it later in folder properties.

Note that synchronization does not happen automatically, you have to click `Synchronization > Save All` on the toolbar
or `Save` in the context menu of the request or folder. [Here](https://github.com/AntonShuvaev/jet-client-support#git-sync) is some documentation.
