### ISSUE TITLE
Add GraphQL support

### ISSUE THREAD

**Issue by anadale** [AntonShuvaev/jet-client-support#30]
### Is your feature request related to a problem?

While it is technically possible to execute GraphQL requests, you have to manually write JSON request with GraphQL payload as a string without syntax highlighting and autocomplete.

### Describe the solution you'd like

It will be very convenient to have the following features, that will help with GraphQL requests:

- GraphQL Text body format to get a syntax highlighting/autocomplete from existing GraphQL plugin
- Proper JSON request payload construction if GraphQL format is selected
- Request variables (same as folder/global variables, but for this request with the priority in resolution) – and this one maybe helpful not only for GraphQL

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. Will add to the roadmap.

**Comment by anadale** [comment]
@AntonShuvaev, thank you, great job! One thing, though - it doesn't picks up existing GraphQL configuratin file and keeps suggesting to create a new one over and over again :-(

**Comment by AntonShuvaev** [comment]
@anadale Could you specify which IDE and version you are using?

**Comment by anadale** [comment]
JetBrains Rider 2024.1 EAP 9
Build #RD-241.14494.107, built on March 15, 2024
Runtime version: 17.0.10+8-b1207.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
.NET Core v8.0.1 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
  actionSystem.fix.alt.gr=false
  search.everywhere.settings=true
  ide.experimental.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  fluentvalidation-rider (2024.1.0-eap01)
  dev.turingcomplete.intellijdevelopertoolsplugins (4.0.0)
  com.intellij.resharper.HeapAllocationsViewer (2024.1.0-eap01)
  org.intellij.plugins.hcl (241.14494.150)
  org.toml.lang (241.14494.150)
  com.intellij.apacheConfig (241.14494.159)
  com.jetbrains.space (241.14494.150)
  verify-rider (2024.1.0-eap01)
  org.turbanov.run.configuration.as.action (2.2)
  cognitivecomplexity-rider (2024.1.0-eap01)
  com.codeium.intellij (1.8.14)
  String Manipulation (9.12.0)
  Abc.MoqComplete.Rider (2023.3.0.1)
  org.intellij.RegexpTester (2.2.0)
  com.intellij.mermaid (0.0.20+IJ.232)
  com.intellij.kubernetes (241.14494.150)
  com.intellij.grazie.pro (0.3.292)
  com.intellij.ml.llm (241.14494.158)
  com.intellij.bigdatatools.core (241.14494.158)
  com.intellij.bigdatatools.binary.files (241.14494.158)
  com.intellij.bigdatatools.rfs (241.14494.158)
  com.intellij.lang.jsgraphql (241.14494.150)
  io.jetclient (2024.1.2-241)
  cn.yiiguxing.plugin.translate (3.5.7)
  org.jetbrains.plugins.docker.gateway (241.14494.150)

**Comment by AntonShuvaev** [comment]
Try version 2024.1.3. It should be fixed now.
