### ISSUE TITLE
Setting Environment Variable not working properly for imported postman collection or other

### ISSUE THREAD

**Issue by sandeshfromindia** [AntonShuvaev/jet-client-support#36]
**Describe the bug**
If I import collection from Postman and in request test script I write some code to store response output in some variable ,so that variable defining is not happening properly.
refer below code
jc.folderVariables.setLocalEnv("api-auth-token-external", aaaggtokenValue.data.token);

This was converted from postman  testscript to JC script 
but when I run the API new variable gets created like 
{
api: {
      auth: {
        token: {
          external: "some value"
        }
      }
    } 
}

Instead, it should be stored as 
{
"api-auth-token-external": "some value"
}

**Environment information:**
- OS: MAC
- IDE version: WebStorm 2023.1.3
- plugin version: 2023.1.15-231

**Comment by AntonShuvaev** [comment]
Fixed
