### ISSUE TITLE
Please support for WebStorm build 232.*+

### ISSUE THREAD

**Issue by valentin78** [AntonShuvaev/jet-client-support#37]
getting issue while trying install plugin in WebStorm recent version

![err-ws](https://github.com/AntonShuvaev/jet-client-support/assets/4290501/3b925e72-33e0-492a-bb2c-cc1261f6ca91)

**Comment by AntonShuvaev** [comment]
Could you provide more details about the issue you're facing?

**Comment by valentin78** [comment]
just try install plugin into recent version of Webstorm

**Comment by AntonShuvaev** [comment]
By 'recent version,' do you mean the EAP 2023.3 version or 2023.2.2?

**Comment by valentin78** [comment]
2023.2.2
https://www.jetbrains.com/webstorm/download/other.html

**Comment by AntonShuvaev** [comment]
Please update the plugin to version 2023.1.15-232. I release separate plugin versions for each IDE version. So, for IDE version 2023.2.2, you'll need a plugin version that ends with 232.
