### ISSUE TITLE
Syntax highlighting in Pre-request and Test 

### ISSUE THREAD

**Issue by valdemar1977** [AntonShuvaev/jet-client-support#38]
### Is your feature request related to a problem?

No syntax highlighting in Pre-request and Test 

### Describe the solution you'd like

Please add a syntax highlighting in Pre-request and Test

**Comment by AntonShuvaev** [comment]
Syntax highlighting is enabled in IDEs that offer JavaScript support. However, it is not available in IntelliJ IDEA Community edition and Android Studio, which lack this support.
