### ISSUE TITLE
History akin to what the default Http client generates

### ISSUE THREAD

**Issue by yilativ** [AntonShuvaev/jet-client-support#41]
### Is your feature request related to a problem?

I'd like to keep a record (and do comparisons) between different results from the response.. The default http client generates file based results. Those results are available to be reviewed at a later time. 

### Describe the solution you'd like

Allow for the results to be saved automatically into a history like feature that the regular Http client generates.

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion. This is definitely must-have feature. I will add it to the roadmap.

**Comment by AntonShuvaev** [comment]
Released in 2024.1.0
