### ISSUE TITLE
Support for secret values to prevent commiting them to repository

### ISSUE THREAD

**Issue by FercoCQ** [AntonShuvaev/jet-client-support#44]
### Is your feature request related to a problem?

Security issues may arise due to commiting secret keys or passwords to a VCS.

### Describe the solution you'd like

A way to define variables with secret values, so they aren't commited to the repository even if the `Save` functionality is used.
As a partial solution, these values could be stored in a folder that isn't typically commited, like the `.idea` folder.

**Comment by AntonShuvaev** [comment]
Hello,

The variables are separated into 'Local' and 'Shared'. Shared variables are saved in sync files, while local variables are securely stored on your machine. This way, sensitive information like secret keys or passwords is not committed to the VCS.
