### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by darwin-buelo** [AntonShuvaev/jet-client-support#45]
### Is your feature request related to a problem?

I am using Jet client for testing of my api endpoint. It would be really helpful to some how write documentation about my api to help me remember of the payloads that are optionals and possible values. It would also be nice or good to have if that documentation could be exported in openapi

### Describe the solution you'd like

I am using Jet client for testing of my api endpoint. It would be really helpful to some how write documentation about my api to help me remember of the payloads that are optionals and possible values. It would also be nice or good to have if that documentation could be exported in openapi

**Comment by AntonShuvaev** [comment]
Thank you for your suggestion. Including markdown documentation for requests and folders is on my roadmap. I plan to implement this feature in the near future.

**Comment by tukusejssirs** [comment]
I am also interested in an option to document URL parameters, body, headers, auth, scripts, general API documentation. I like how [Insomnia](https://insomnia.rest/) has done, but I dislike their new cloud stuff which is why I am switching to JetClient which I like, but it misses some features.

**Comment by AntonShuvaev** [comment]
@tukusejssirs, JetClient supports custom documentation in Markdown, accessible through the JetClient Tools toolwindow. It includes both auto-generated and custom content. See the screenshots below:
 
![CleanShot 2025-01-01 at 23 29 44@2x](https://github.com/user-attachments/assets/0b4a70cf-cd8a-4f0f-93d4-8159a49d7470)
![CleanShot 2025-01-01 at 23 33 00@2x](https://github.com/user-attachments/assets/d928a0cf-aac5-4fb7-bfde-b4c68116cc9a)
