### ISSUE TITLE
JetClient on Mac not using colorization  or completion

### ISSUE THREAD

**Issue by jdblack** [AntonShuvaev/jet-client-support#48]
**Describe the bug**
The test console for writing tests does not show color, syntax highlighting or  completion when writing tests. This makes learning how to use jetclient very difficult as there doesn't seem to be any documentation online for this tool.

Outside of Jetclient,  things work normally as expected.

![Screenshot 2023-12-10 at 9 46 56 PM](https://github.com/AntonShuvaev/jet-client-support/assets/1109549/63b84094-e69b-4bd9-9061-a1ed70a8cc27)

**Expected behavior**
I would expect color highlighting and  online documentation similiar to the youtube documents at https://youtu.be/hLPhPuoYjCY?si=REJM3ssi4JcBVXZn&t=377

**Environment information:**
JetClient : 2023-01-15-223
Android Studio Giraffe | 2022.3.1 Patch 1
MacOS 14.1 (Sonoma)

- OS:
- IDE version:
- plugin version:

**Comment by AntonShuvaev** [comment]
The code completion for Pre-request and Test scripts in the JetClient plugin depends on the JetBrains JavaScript plugin, which is available only in the paid versions of IntelliJ IDEs. Unfortunately, this feature is not supported in free editions, such as IntelliJ IDEA Community Edition and Android Studio.
