### ISSUE TITLE
Allow Binary as a POST body type

### ISSUE THREAD

**Issue by diquah** [AntonShuvaev/jet-client-support#50]
### Is your feature request related to a problem?

Currently, to send binary data I have to create and pick a file. However, my application uses many small binary packets in place of JSON. In order to simulate these requests I would have to make a file for every type of POST request.

### Describe the solution you'd like

It would be really neat to have a "binary" type where hexadecimal or base-64 encoded binary could be submitted into the input box for the body, which would then be converted into a raw byte array for transit.

Inputting binary in hex form would look like this:
`83 A3 69 6E 74 01 A5 66 6C 6F 61 74 CB 3F E0 00 00 00 00 00 00 A7 62 6F 6F 6C 65 61 6E C3`

And Base64 like this:
`gqVoZWxsb6V3b3JsZKRib29sww==`

Inputting binary data would have be in a text form because it needs to be represented somehow, but having to save a file for each message really disrupts from the flow of having everything in the editor.

**Comment by AntonShuvaev** [comment]
I've added Binary Base64 body type. Hex support wasn't added because it's less common and easily converted to Base64.
