### ISSUE TITLE
Curl import errors

### ISSUE THREAD

**Issue by rickythefox** [AntonShuvaev/jet-client-support#53]
**Describe the bug**
Importing the following curl results in two errors:
1. The JSON string is not unescaped in the JSON body view.
2. When trying to send the request JetClient complains that the Content-Length is present twice and no request is made unless you remove the imported header.

**Steps to reproduce**
Import this curl by pasting it into the address field:

```
 curl \
 -X POST \
 -H "Content-Length: 123" \
 -H "Content-Type: application/json; charset=UTF-8" \
 --data "{\"id\":\"b2f1c32b\"}" \
 "https://foo.com"
```

**Expected behavior**
1. Should parse JSON if Content-Type is set to application/json
2. Should remove the extra Content-Length? Or not add an automatic one?

**Environment information:**
- OS: MacOS
- IDE version: Build #PY-232.9559.58, built on August 22, 2023
- plugin version: 2024.1.0-232

**Comment by AntonShuvaev** [comment]
Thanks for reporting this! Will fix in the next update.

**Comment by AntonShuvaev** [comment]
The issue has been resolved. Now, the Content-Length header is ignored during cURL import, and quote escaping is removed from the JSON body.
