### ISSUE TITLE
Invalid encoding of GraphQL requests

### ISSUE THREAD

**Issue by anadale** [AntonShuvaev/jet-client-support#55]
**Describe the bug**
When request with GraphQL body is executed, Unicode strings are not properly encoded. For example, Cyrillic symbols are converted to question marks (see attached images).

**Steps to reproduce**
- Create new request
- Select "GraphQL" in the body type dropdown
- Write a GraphQL request that either have an embedded string with Cyrillic letters as a parameter or references variable, that have a string with Cyrillic letters as a field
- Execute a request

**Expected behavior**
Data has been properly encoded (as UTF-8)

**Environment information:**
- OS: MacOS
- IDE version: JetBrains Rider 2024.1 EAP 9
- plugin version: 2024.1.2-241

![gql-encoding-1](https://github.com/AntonShuvaev/jet-client-support/assets/761097/ca3e25dd-cab6-4f17-8979-06de10122a13)
![gql-encoding-2](https://github.com/AntonShuvaev/jet-client-support/assets/761097/554016e4-e0f8-4483-83f3-e4c7a4d7564a)

**Comment by AntonShuvaev** [comment]
Thanks for reporting this issue. The bug is fixed in version 2024.1.3.
