### ISSUE TITLE
Automatically send Content-Length

### ISSUE THREAD

**Issue by amadeusmz** [AntonShuvaev/jet-client-support#56]
### Is your feature request related to a problem?

Some requests requires length. When use Jetclient to call such requests, they'll return 411.

### Describe the solution you'd like

Automatically send Content-Length like Postman or Jetbrains HTTP clients

**Comment by AntonShuvaev** [comment]
@amadeusmz Could you provide steps to reproduce? I checked with `https://httpbin.org/anything` and saw the `Content-Length` header is sent.

**Comment by amadeusmz** [comment]
@AntonShuvaev I see no `Content-Length` went sending requests with Jetclient, see image

![idea64_KlnYYIMglT](https://github.com/AntonShuvaev/jet-client-support/assets/15067059/b3dd159c-8546-4308-b548-73eedcc1f013)

**Comment by AntonShuvaev** [comment]
@amadeusmz,  thank you for the details. I will implement the addition of the `Content-Length: 0` header for requests with an empty body and for methods other than GET in the next update.

**Comment by AntonShuvaev** [comment]
Fixed in version 2024.1.5.
