### ISSUE TITLE
Discord Server / Channel

### ISSUE THREAD

**Issue by tobiashochguertel** [AntonShuvaev/jet-client-support#59]
### Is your feature request related to a problem?

Get Quick help with JetClient, share knowledge with other users etc.

### Describe the solution you'd like

A discord channel where I can ask questions and get answers. I like Discord more than slack because it doesn't require a subscription to see the whole log of a channel. Many open-source projects maintain a discord channel, and I can recommend it. Have good experience with it.

**Comment by AntonShuvaev** [comment]
Thank you for the suggestion! I'll definitely set up a Discord channel for JetClient. I'll update this issue once it's created.

**Comment by AntonShuvaev** [comment]
Created a Discord server for JetClient: [Join here](https://discord.gg/23hufAcU8n).
