### ISSUE TITLE
When adding a JWT token a space is inserted in the beginning

### ISSUE THREAD

**Issue by rickythefox** [AntonShuvaev/jet-client-support#6]
### Describe the Issue

When adding a JWT token a space is inserted in the beginning of the token.

### Steps to reproduce?

```Markdown
1. Create a request with a JWT token in Auth tab (select Token).
2. Paste JWT
3. Send request

Checking the token on the server shows that a space was added in the beginning. .strip() on the server removes the space and makes it work.
```

### Operating System

MacOS

### IDE

Pycharm 2022.3.3 Pro

### JetClient version

2023.1.4-223

**Comment by AntonShuvaev** [comment]
I cannot reproduce this bug. I've tested by sending a request with token `test` to `https://httpbin.org/anything`
and got `"Authorization": "Bearer test"` in the response. See the screenshot:
![Untitled](https://user-images.githubusercontent.com/25157138/227193343-1805e6b4-667c-4877-9d02-042249357d83.jpg)

Can you please do the same test and double check that you are using the correct token?

**Comment by rickythefox** [comment]
You're right, it was copy/paste issue. 

However it might make sense to trim the whitespace on the entered token before sending it? I'm not sure if a JWT starting or ending with a space is valid standard-wise
