### ISSUE TITLE
Record sent variables value in request history

### ISSUE THREAD

**Issue by amadeusmz** [AntonShuvaev/jet-client-support#61]
### Is your feature request related to a problem?

My requests contains variables, and their values are not recorded when sending requests.

### Describe the solution you'd like

I want to know what value are sent in requests history.

**Comment by AntonShuvaev** [comment]
Thanks for the feature request. I'm planning to implement a console (similar to the Postman console) where all requests and responses will be logged.

**Comment by AntonShuvaev** [comment]
Version 2024.1.6 now includes a console in the Services tool window for viewing requests, responses, and script output.
