### ISSUE TITLE
jc.response.to.be.error fails the test if the http code is 400-599

### ISSUE THREAD

**Issue by L10nhunter** [AntonShuvaev/jet-client-support#62]
**Describe the bug**
The test should pass if the response is an error code, instead it fails. Hilariously, the fail message says that its bugged outright: "AssertionError: expected response code to be '4XX' or '5XX' but found 401"

**Steps to reproduce**
create a test designed to make sure that the http response is an error code, and test for error.

jc.test("Login User Fail", () => { jc.response.to.be.error })

**Expected behavior**
the test should pass.

**Environment information:**
- OS: Windows 11 Home Version 10.0.22631 Build 22631
- IDE version: 2024.1
- plugin version: 2024.1.5-241

**Comment by AntonShuvaev** [comment]
Thanks for reporting this bug. I'll fix it in the next update.
