### ISSUE TITLE
Jet Client issue with Intelij Idea Ultimate Build #IU-241.14494.240

### ISSUE THREAD

**Issue by yashraj9501** [AntonShuvaev/jet-client-support#65]
**Describe the bug**

Plugin gets crashed or not loading the newly API added, everytime when I create a new API and I re-import the same, that particular API do not gets loaded even after multiple click, it gets imported but not able to run it, need to restart the IDE everytime then it works properly

**Steps to reproduce**

1. Create a new API in Spring boot application
2. Sync the APIs with Jet client.
3. Now, after syncing for the first time, again add a new API.
4. Go for the re-import option in JetClient.
5. Now, try to open the newly fetched API, it is not getting opened to that I can run that.
6. Now, to run the newly fetched API, please restart the IDE.
7. After restarting, it will work fine.

**Expected behavior**

Before this latest update, the Jet client was working fine

**Environment information:**
- OS: Windows
- IDE version: #IU-241.14494.240
- plugin version: 2024.1.6-241(Paid)

**Comment by AntonShuvaev** [comment]
Thanks for reporting this bug. Will fix it in the next update.
