### ISSUE TITLE
Getting error "Parameter specified as non-null is null: method kotlin.text.StringsKt__StringsJVMKt.isBlank, parameter <this>"

### ISSUE THREAD

**Issue by dudatom4** [AntonShuvaev/jet-client-support#66]
**Describe the bug**
I do not know where the problem is. But when i try to log in client to my aplication its all fine. 
I got response code 200 with all informations in response body.
But when i try to log in for example with incorrect password or with client witch does not exists it ends with the error
"Parameter specified as non-null is null: method kotlin.text.StringsKt__StringsJVMKt.isBlank, parameter <this>"

When i try it in Postman its all fine. I got status 460 with all informations in response body why the client doesnt log in.

I think that there might be problem with response code statuses 450+ and 460+.
All others works fine for me.

My endpoints is not public so i can not provide specific informations about calls.

Is it bug or am i doing something wrong?

**Environment information:**
- OS: Windows
- IDE version: Runtime version: 17.0.10+8-b1207.12 amd64
- plugin version: 2024.1.6-241

**Comment by AntonShuvaev** [comment]
Thanks for reporting this bug. I'll have it fixed in the next update, scheduled for next week.
