### ISSUE TITLE
Dragging a JetClient tab outside of the Rider closes the tab

### ISSUE THREAD

**Issue by FercoCQ** [AntonShuvaev/jet-client-support#67]
**Describe the bug**
When you drag a tab from the IDE to outside of it, it normally creates a new "detached window" with that tab. Currently you cannot do that with a JetClient tab, the tab is closed/lost when you release the mouse button. At the moment it works if the detached window already exists, for example, with a tab with some source code. It also works if there is already a detached window with some JetClient tab, even if you release the new tab outside of it, creating a second detached window.
I believe this might be related to some cases of losing opened tabs when restoring a workspace, since I had all JetClient tabs together by themselves in a detached window. I haven't confirmed it though.

**Steps to reproduce**
1.- Open a JetClient request
2.- Drag the opened tab outside of the IDE

**Expected behavior**
A new window should be created with the tab that was dropped. This worked without problem a few releases ago.

**Environment information:**
- OS: Windows 10
- IDE version: Rider 2024.1.1, Build #RD-241.14494.325
- plugin version: 2024.1.6-241

**Comment by AntonShuvaev** [comment]
It seems this issue might be related to JetBrains IDEs behavior, affecting all types of files. If there's only one tab open, it seems you can't drag it to create a new window, but with more than one tab, it appears possible. As a workaround, you can use "Move Tab to New Window" (Shift + F4) action.
