### ISSUE TITLE
Curl import

### ISSUE THREAD

**Issue by rickythefox** [AntonShuvaev/jet-client-support#7]
### Is your feature request related to a problem?

Should be easier to add curl requests.

### Describe the solution you'd like

Would be great to be able to paste a curl command into the url and get all the params parsed and imported. Check Insomnia.

**Comment by AntonShuvaev** [comment]
This is already possible. `New > Import > cURL` will import one or more cURL commands into new requests.

**Comment by AntonShuvaev** [comment]
Curl import from URL field is now supported, please update to 2023.1.5.
