### ISSUE TITLE
Folder not selectable

### ISSUE THREAD

**Issue by schoenbergerb** [AntonShuvaev/jet-client-support#72]
**Describe the bug**
I want to create a project with local file sync, but I keep getting the error message 'not a directory' in the dialog. 
It doesn't work whether I use an absolute or relative path. I tried it with different names as well (with minus, without, with underscore, ...).
Am I doing something wrong or is there a bug here?

**Steps to reproduce**
In the screenshot you can see the "empty-folder" exists, but I can't select it.
![Bildschirmfoto 2024-05-14 um 12 21 45](https://github.com/AntonShuvaev/jet-client-support/assets/5960337/0f27237d-2aef-4c42-af5f-fdd0e070f2a8)

**Expected behavior**
It just should work like expected 😅

**Environment information:**
- OS: Mac (M1)
- IDE version: PhpStorm 2024.1.1
- plugin version: 2024.2.1-241

**Comment by AntonShuvaev** [comment]
Thanks for reporting. Will fix asap.

**Comment by AntonShuvaev** [comment]
The bug has been fixed, please update to version 2024.2.2
