### ISSUE TITLE
No serializer found for class io.jetclient.jM and no properties discovered to create BeanSerializer

### ISSUE THREAD

**Issue by johanneslietz** [AntonShuvaev/jet-client-support#75]
**Describe the bug**
When I try to to any request, I login via oauth, get the callback and "Your call is authenticated", but instead of a response I get an error tab saying:

Could not send request
No serializer found for class io.jetclient.jM and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)

**Steps to reproduce**
Setup a request with oauth, send the request, login via oauth.

**Expected behavior**
Plugin performs the request and shows the result of the request.

**Environment information:**
- OS: Windows 10 Enterprise 22H2
- IDE version: 2024.1.2 Ultimate
- plugin version: 2024.2.3-241

**Comment by AntonShuvaev** [comment]
Thanks for reporting. Will fix ASAP.
