### ISSUE TITLE
Environmet variables are broken

### ISSUE THREAD

**Issue by Iworb** [AntonShuvaev/jet-client-support#79]
I have 2 environments: stage and production. So I've created both of them and assigned the names 'bb_stage' and 'bb_prod'. I set up all the shared and local variables, but after the recent update it looks like it can't find any variable. Also, I'm unable to change the alias of my environment anymore, and changing the order of the environments won't let you set it back easily. It looks like the state wasn't updated.
<img width="739" alt="image" src="https://github.com/AntonShuvaev/jet-client-support/assets/6623262/fa9a1de0-4813-4c8c-80aa-e0fbd15994a6">
<img width="682" alt="image" src="https://github.com/AntonShuvaev/jet-client-support/assets/6623262/21e287ba-45a6-4bee-92ce-e437acda7c56">

**Steps to reproduce**
Create environments on the old version of the plugin and then update the plugin.

**Expected behavior**
Variables in the environment should be usable.

**Environment information:**
- OS: Win 11
- IDE version: 2024.1.3
- plugin version:2024.2.4-241

**Comment by AntonShuvaev** [comment]
Hi, 

The migration to the new version may require some manual adjustments.

Regarding the variables, you can only reuse variables that are defined within the same folder or parent folders. To resolve your problem, you can define environment variables in the project (top folder) where you set `baseUrl` in `globals`, or move `baseUrl` to the folder where `endpoint` is defined and put it at the top level without specifying an environment or using `globals`.

Aliases were removed for simplicity. You can now use the environment name directly, or a lowercase version with spaces replaced by underscores.

I couldn't fully understand the part about changing the order of environments, but I found a bug with the "Move down" button not working in the Environments tab. I will fix this in the next update.

**Comment by Iworb** [comment]
However, the main key is to build the "baseUrl" from the environment-specific variables. In my case, I have a static prefix and a dynamic endpoint. That's why I declared "basuUrl" in the "globals" (ex. "default") directory.

Aliases were really handy. Environment names are long sometimes, that's why short names were the better option IMO.

The sorting issue is kinda easy to reproduce:
1. Open the Environment Manager;
2. Create 2 environments;
3. Select the 2nd one;
4. Click on the "Move Up" button. Now it's first;
5. Select the 1st one and click "Move Down". Nothing happened, it stays on the first place unless you move another item.

**Comment by AntonShuvaev** [comment]
Thanks for the details. I will fix the issue with resolving folder variables in environment variables in the next update. I will also bring back the aliases for environments and fix the ordering issue.
