### ISSUE TITLE
Add a way to visualize logging done in pre-requests and tests

### ISSUE THREAD

**Issue by GauthierPLM** [AntonShuvaev/jet-client-support#8]
### Is your feature request related to a problem?

When building a pre-request or test script, it is common to use console.log() and similar functions to debug the JS code executed. Currently, there is no way to visualise these logs from the IDE (currently using DataGrip).

### Describe the solution you'd like

A panel displaying the logs produced from pre-requests and tests. It might be part of the visualization described in #2, or a dedicated tool window (but I am not sure adding tool window is the most UX friendly way to approach this). 

### Additional context

With this issue and #2, the plugin would have a visualization similar to Postman' console.

**Comment by AntonShuvaev** [comment]
The output of `console.log` is displayed along with test results. But I agree that it is not very convenient and I plan to show it in the service tool window, as you described.

**Comment by AntonShuvaev** [comment]
Version 2024.1.6 now includes a console in the Services tool window for viewing requests, responses, and script output.

**Comment by lsalazarm99** [comment]
Hello @AntonShuvaev! I have a `console.log` in the scripts of the pre-request and post-request, but there is no console in the services tool. I'm using the 2024.3.17-243 version of the plugin, free license.

**Comment by AntonShuvaev** [comment]
Hello @lsalazarm99, I’ve moved it from the Services tool window to a separate JetClient Console tool window.
![CleanShot 2024-11-22 at 20 37 28@2x](https://github.com/user-attachments/assets/771518f6-dfed-40c6-962e-9843b728ea0f)
