### ISSUE TITLE
Environment doesn't persist across requests

### ISSUE THREAD

**Issue by Iworb** [AntonShuvaev/jet-client-support#80]
When I'm selecting an environment I expect that if I open another request I will be in the same environment as I was. I've imported ~100 requests and selected the "Stage" environment, but when I switched to another request I found out that the environment was reset to the "No Environment".

**Steps to reproduce**
Crea a project with multiple environments and requests. Select the environment in one request and then select an another request.

**Expected behavior**
Environment shouldn't be the part of the request's settings. That's why it's called "Environment".

**Environment information:**
- OS: Win 11
- IDE version: 2024.1.3
- plugin version:2024.2.4-241

**Comment by AntonShuvaev** [comment]
Thank you for reporting this issue. The current behavior is that new requests are opened with the last selected environment, but changing the environment in one tab doesn't affect other tabs. The initial idea was to allow selecting different environments simultaneously on different tabs. However, this is rarely needed and can be confusing. I agree that it looks like a bug, and I will fix this in the next update.
