### ISSUE TITLE
Show the whole raw request detail while calling

### ISSUE THREAD

**Issue by joshuaguo1986** [AntonShuvaev/jet-client-support#81]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Hi team,

I have to say JetClient is the perfect replacement of Postman! However it will be more great if you can add this feature. Like the console of Postman, while sending a request, sometimes I need to check the whole detail of the raw request (with all variables replaced), including URL, request payload and request headers. So is it possible to add this?
Thanks.

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion! I'm planning to release the request preview feature next week. Additionally, there is a console in the Services tool window, which I plan to improve in the next update.

**Comment by joshuaguo1986** [comment]
@AntonShuvaev  Great! Looking forward for it!
