### ISSUE TITLE
Support importing JAX-RS from `jakarta.ws.rs` namespace

### ISSUE THREAD

**Issue by jimmydivvy** [AntonShuvaev/jet-client-support#82]
### Is your feature request related to a problem?

JetClient can import routes directly from a project with JAX-RS annotated controllers, however this appears to only work with the older `javax.ws.rs` namespace.

This has since been renamed to `jakarta.ws.rs`, which JetClient doesn't appear to recognize

### Describe the solution you'd like

JetClient can automatically recognize and import jax-rs resources annotated with the new `jakarta.ws.rs` namespaced annotations.

**Comment by AntonShuvaev** [comment]
Thank you for reporting this issue. I'll fix it in the next update.
