### ISSUE TITLE
General issues after updating to 2024.2.6-241

### ISSUE THREAD

**Issue by FercoCQ** [AntonShuvaev/jet-client-support#83]
**Describe the bug**
I just updated JetClient to the latest version (2024.2.6-241) and there are a lot of issues.

1. If I click on a request, the openAPI JSON definition is opened instead of the usual window to run the request. I have to doble click it twice for it to open.
2. After I open the request with double double click, it's copied to the Drafts section, and so, it doesn't recognize any of the project environments and their variables.
3. I can't import the openAPI file again, there is no option in the "Import" menu.
4. If I right click the project folder, the project settings are opened, and the old openAPI file I imported is in the "API" section, but if I import it again, it has the same issues.

**Steps to reproduce**
I just updated, there aren't steps really.

**Expected behavior**
I should be able to run a request I have in the project, with the project environments and variables.

**Environment information:**
- OS: Windows 10
- IDE version: JetBrains Rider 2024.1.3 (Build #RD-241.17011.166)
- plugin version: 2024.2.6-241

**Comment by AntonShuvaev** [comment]
I've recently changed the behavior of importing. Now, you need to add the API in the APIs tab of the project. Then, endpoints will be shown in the project tree. They are not opened as usual requests because they are built dynamically from the code or OpenAPI file. Because of this, they are opened as drafts on double-click.

To use them as usual requests, drag and drop them into the needed requests collection. Thank you for bringing this up, I'm planning to also add the previous import functionality as it seems more intuitive. I haven't updated the documentation yet but will do so soon.

**Comment by FercoCQ** [comment]
Ok, so the steps would be:

1. Import the openAPI through the project settings
2. Create an empty project folder
3. Drag the imported requests to your folder?

Can you explain the reasoning? The only one I can think of is to keep the imported one on sync with the file without having to mess with your copy. Is that the reason?

If that's the case, maybe you can consider making non modifiable sections inside the project tree, where you clearly separate what's not direcly usable (the imported openAPI) and your actual requests. Currently they are both "just folders", so it's very confusing why they behave differently.

Also, you mentioned "built dynamically from the code"? That has **never** worked for me, no matter how many different ways I try to do it. If you're updating the documentation, maybe you can add that too?

**Comment by AntonShuvaev** [comment]
The steps you mentioned are correct. I added the APIs to the project tree for the following reasons:
- The request collection can have multiple copies of requests and numerous additional folders, whereas the API provides a straightforward structure of all endpoints, making it convenient for viewing and navigating.
- Previously, the re-import functionality didn't work correctly when requests had a different folder structure than when they were first imported or when modifications were made to requests. It was challenging to merge them correctly, so users had to do it manually by importing everything into a new folder and then moving the newly added requests to the desired location.

With the new method, when you add an endpoint to the OpenAPI file, you simply need to click the refresh button in the project tree, and the new endpoints will appear. You can then move them as needed.
Currently, API folders in the project tree have a different icon than usual folders, but I agree that this distinction could be made clearer.

Regarding "built dynamically from the code" I mean that when you add a new endpoint in the OpenAPI file (or a Spring Controller, or others) and click refresh, it will be added to the API folder in the project tree. However, it doesn't have a persistent state like usual requests.

**Comment by FercoCQ** [comment]
Thanks, that makes sense. I'm looking forward for the updated documentation.
