### ISSUE TITLE
JetClient folder appears under .idea folder when JetClient is not used

### ISSUE THREAD

**Issue by daveyostcom** [AntonShuvaev/jet-client-support#84]
In my Rider solution folder, under its .idea folder, there is a JetClient folder containing files, even though JetClient isn’t even applicable.

**Steps to reproduce**
Make a new .NET solution with a console app in it.  Apparently.

**Expected behavior**
No JetClient folder

**Environment information:**
- OS: macOS
- IDE version: Rider 2024.1.2
- plugin version:  2024.2.4-241

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will fix it in the next update.
