### ISSUE TITLE
jc.request.set/remove header are without effect - Overall intention is to clear cookies before each call

### ISSUE THREAD

**Issue by RAlfoeldi** [AntonShuvaev/jet-client-support#85]
**Describe the bug**
Overall intention is to NOT send cookies. Cookie Manager allows for deleting cookies manually, but not for preventing cookies being set.

As workaround I've tried using pre request scripts with

`` 
jc.request.setHeader("Cookie", '');  
jc.request.removeHeader("Cookie");
``

etc. in all kinds of variants to no effect.

**Steps to reproduce**
see above

**Expected behavior**
No cookies in request.

**Environment information:**
- OS: windows
- IDE version: WebStorm 2024.1.5
- plugin version: 2024.2.6-241

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will add methods for managing cookies in the library and implement per-request settings for disabling cookies.

**Comment by AntonShuvaev** [comment]
Added `jc.cookies.*` methods for cookie management in scripts. Also added a `Disable cookie jar` option to folder settings.
