### ISSUE TITLE
Error when trying to use OAuth2

### ISSUE THREAD

**Issue by FercoCQ** [AntonShuvaev/jet-client-support#86]
**Describe the bug**
An error is shown when trying to get a new access token for an OAuth2 authentication. I'm copying the configuration exactly as a co-worker has it working on Postman, so the values themselves shouldn't be the issue.

**Steps to reproduce**

1. Fill the OAuth2 authorization as in the following image. The variables are in my environment, but I tried using the values directly and the same error is shown.
![OAuth2_error](https://github.com/AntonShuvaev/jet-client-support/assets/26574944/58fbfbc3-1e90-4474-bdc9-1de128c7af47)
2. Click on "Get New Access Token".

**Expected behavior**
The new access token and refresh token should be retrieved.

**Environment information:**
- OS: Windows 10
- IDE version: Rider 2024.1.3 (Build #RD-241.17011.166)
- plugin version: 2024.2.6-241 and 2024.2.7-241

**Comment by AntonShuvaev** [comment]
Thanks for reporting. Will fix it in the next update.
