### ISSUE TITLE
Sometimes IDE Frozen in php kint big objects

### ISSUE THREAD

**Issue by Jhon-Henkel** [AntonShuvaev/jet-client-support#87]
**Describe the bug**
Sometimes when i use  kint debug tool, when object is big, the IDE frozen. Infinite status sending request and impossible to use IDE

**Steps to reproduce**
Just debug with kint php tool big objects.

**Expected behavior**
My IDE don't frozen.

**Environment information:**
- OS: Ubuntu 23.10
- IDE version: 241.18034.69
- plugin version: 2024.2.6-241

**Comment by AntonShuvaev** [comment]
Thanks for reporting this issue. I'll investigate it.

**Comment by AntonShuvaev** [comment]
The issue has been fixed. Please update the plugin to the latest version. Let me know if you still experience any problems.
