### ISSUE TITLE
ClassCastException after OAuth2 login

### ISSUE THREAD

**Issue by johanneslietz** [AntonShuvaev/jet-client-support#88]
**Describe the bug**

When returning from a OAuth login in the browser, the JetClient does not perform any requests, but shows the following error message:

java.lang.ClassCastException: class org.apache.hc.core5.http.message.BasicHttpResponse cannot be cast to class org.apache.hc.client5.http.async.methods.SimpleHttpResponse (org.apache.hc.core5.http.message.BasicHttpResponse and org.apache.hc.client5.http.async.methods.SimpleHttpResponse are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4cd90480)

**Steps to reproduce**
1. Start a request with OAuth
2. Login in Browser
3. Return to IDE

**Expected behavior**
JetClient performs the request and shows result

**Environment information:**
- OS: Windows 11
- IDE version: IntelliJ IDEA 2024.1.4 (Ultimate Edition)
- plugin version: 2024.2.7-241

**Comment by AntonShuvaev** [comment]
I've just released a fix for the issue. Please update to version 2024.2.8

**Comment by johanneslietz** [comment]
Works again, thanks for the quick fix!
