### ISSUE TITLE
Could not send request - StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION

### ISSUE THREAD

**Issue by RAlfoeldi** [AntonShuvaev/jet-client-support#89]
**Describe the bug**
Query:
{{baseUrl}}{{squidScope}}{config}?limit=10&showBlank

Adding a query param 'showBlank' to a request causes error mentioned below.
Bizarrely this only happens with some values of 'config'.
config = 'alm_asset' => OK.
config = 'incident' => Error

Disabling 'showBlank' and everything is fine. 

**Steps to reproduce**
See above.

**Expected behavior**
No error :-)

**Environment information:**
- OS: Windows
- IDE version: Build #WS-241.18034.50, built on June 19, 2024
- plugin version: 2024.2.8-241

Unexpected end-of-input: expected close marker for Array (start marker at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 371])

**Comment by RAlfoeldi** [comment]
My bad. The problem is in the returned JSON that isn't well structured.

However the error message is misleading.

**Comment by AntonShuvaev** [comment]
Thanks for reporting. I'll fix the error message for incorrect JSON responses.

**Comment by AntonShuvaev** [comment]
Fixed
