### ISSUE TITLE
JetClient should better display when a request is running

### ISSUE THREAD

**Issue by GauthierPLM** [AntonShuvaev/jet-client-support#9]
### Is your feature request related to a problem?

There is currently no clear visual way to know if a request is running as the plugin does not grey the previous response and does not display any spinner in the client. Only the progress of a task in the bottom right of the IDE shows that something is going on.

### Describe the solution you'd like

When a request is run, the response part should be greyed / overlayed by a spinner to clearly let user know a request is ongoing. This could also be used to easily cancel a request in case it takes too long (ex: attempting to run a request that cannot execute because of a networking issue and will timeout only after a minute or two).

**Comment by AntonShuvaev** [comment]
Good point, I will do it.

**Comment by AntonShuvaev** [comment]
Implemented in version 2023.1.6.
