### ISSUE TITLE
Get evaluated body in Pre-request 

### ISSUE THREAD

**Issue by alessandroBalliniGPA** [AntonShuvaev/jet-client-support#91]
### Is your feature request related to a problem?

Body with many variables.
Pre-script needs to get the full evaluated body to generate an auth token

### Describe the solution you'd like

In Pre-Request script a method like "jc.request.body.evaluated"
which returns the body (in the Body Tab) evaluated with variables. 

Example:

Body:
{
"a": 1,
"b: {{var1}}
}

vars:
var1="c"

In Pre-Request script 
jc.request.body.evaluated returns:

{
"a": 1,
"b:  "c"
}

### Additional context

Genearting a body with json ad vars is more user-friendly than generating the sull body in Pre-Script.

**Comment by AntonShuvaev** [comment]
Hi,
You can get what you need by using the `replaceIn` method:
```js
const evaluatedBody = jc.variables.replaceIn(jc.request.body.raw)
```
If you want a shorter version, you can create a global function in your project Init script:
```js
getEvaluatedBody = () => {
    return jc.variables.replaceIn(jc.request.body.raw)
}
```
Then, just use it in your pre-request script like this:
```js
const evaluatedBody = getEvaluatedBody()
```
Hope this helps!
