### ISSUE TITLE
Add support for custom HTTP methods

### ISSUE THREAD

**Issue by FercoCQ** [AntonShuvaev/jet-client-support#92]
### Is your feature request related to a problem?

I need to call an endpoint that uses the experimental `QUERY` HTTP verb, but I can't do it from JetClient.

### Describe the solution you'd like

On the dropdown for selecting the HTTP verb, there could be an "Custom" option, where I could write any HTTP verb as text. I'm not a 100% sure, but I think the only validation should be that it's a string without whitespaces.

**Comment by AntonShuvaev** [comment]
The feature you're requesting is already available. You can specify custom HTTP methods by going to:
`Settings > Tools > JetClient > Custom Methods`
