### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by RAlfoeldi** [AntonShuvaev/jet-client-support#94]
**Describe the bug**
a) after 2-3 requests Jetclient gets very(!) slow. According to own (Jetclient) display requests takes 2-300ms. Jetclient displays result after 5-8 seconds. The first 1-2 requests are a fast as expected. (This happens with minimal JSON payload, < 1k. I would expect longer render times for large JSON payloads > 10MB)
b) WebStorm just crashed with low memory warning and the memory dump points fairly straightly at you.

**Steps to reproduce**
Use Jetclient

**Expected behavior**
- Faster response times
- No memory crashes

**Environment information:**
- OS: macos / Windows 11 - working on both. Happens on both.
- IDE version: Build #WS-241.18034.50, built on June 19, 2024
- plugin version: 2024.3.0-241

**Comment by RAlfoeldi** [comment]
Thanx for the workaround. Semms to do the trick.

**Comment by AntonShuvaev** [comment]
Also, you can set `Max response body size in MB` to 0.0 to avoid storing responses in the request history and reduce `History per request size` to 0 or a small number.

**Comment by AntonShuvaev** [comment]
The issue has been fixed in version 2024.3.2. The request content of large requests is now hidden in the console output and can be opened in a separate tab. Additionally, there is a new setting called `Inline request line limit` that allows you to configure the number of lines displayed inline.
