### ISSUE TITLE
[feature request] OAuth2 Client Credentials Flow

### ISSUE THREAD

**Issue by faelin** [AntonShuvaev/jet-client-support#96]
### Is your feature request related to a problem?

I cannot obtain a bearer token using the Client Credentials flow.

### Describe the solution you'd like

I would love to have a drop-down menu that allows the selection of a Client Credentials flow, which changes the mode in which the token is obtained.

### Additional context

It would also be helpful to have the token dynamically attached to the environment, so that changing the environment changes the token.

**Comment by AntonShuvaev** [comment]
JetClient already supports OAuth2 authentication, including the Client Credentials flow. Here's how you can set it up:
1.	Open the Auth tab of the request or folder
2.	Select "OAuth2" and choose "Client Credentials" as the Grant Type
3.	Enter your Client ID, Client Secret, Access Token URL, and Scopes

Tokens are automatically stored per environment, so switching environments will use the appropriate token for requests.
Let me know if you have any further questions.

**Comment by faelin** [comment]
Oh my goodness, I'm sorry about that! I could have sworn last night that there was no Grant Type drop down, but there it is plain as day!
