### ISSUE TITLE
How to export my requests to cURL

### ISSUE THREAD

**Issue by amadeusmz** [AntonShuvaev/jet-client-support#97]
I remember that there is an option to export my requests to cURL but today I can't find it anywhere.

Is it removed?

**Comment by AntonShuvaev** [comment]
Hi,
You can still export your requests to cURL. See the screenshot:
![CleanShot 2024-08-05 at 13 22 17@2x](https://github.com/user-attachments/assets/2882690c-196d-4d39-85ba-69cfa0cb3e21)
