### ISSUE TITLE
Script not work

### ISSUE THREAD

**Issue by light-developer** [AntonShuvaev/jet-client-support#99]
**Describe the bug**

Script not work (My Response is json, but script still fail (It is good on postman)
Jet Client image: (I use jc. still not work)
![image](https://github.com/user-attachments/assets/017c1acc-efe9-462d-9fe9-6d53d4b44446)
![image](https://github.com/user-attachments/assets/ba151221-2b06-4ee7-8b47-d38c9c063bc7)

Postman image:
![image](https://github.com/user-attachments/assets/00a322d3-74cb-4feb-826c-0065d146609a)
![image](https://github.com/user-attachments/assets/f6d1fd64-aefe-49e4-87ec-4da18ccce5e2)

**Environment information:**
- OS: Windows
- IDE version: PhpStorm 2023.2
- plugin version: 2024.3.5-232

-----------------------------
Other note: Can I create pm variable global (pm = jc) for convenient with postman script when import

**Comment by AntonShuvaev** [comment]
`jc.response` is undefined in the pre-request script. You should write your test in the post-response script.
